# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
