# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20171018_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
