# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_remove_song_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
